# Show suffocation screen when in solid block
no_xray: false

# Disable the ability to fly through blocks
no_noclip: false

# The camera may not leave the first person view (this should be used with no_xray in case the player clips into blocks)
only_first_person: false

# Same as only_first_person except that changing the view to another player is also forbidden
only_recording_player: false

# Hides the coordinates from the F3 screen
hide_coordinates: false

# These can also be configured per-server
servers:
  lobby:
    no_xray: true
    no_noclip: true
  uhc:
    no_xray: true
    only_recording_player: true
    hide_coordinates: true